KNAPSACK-PRO-CLIENT-NAME:
  description: It is the name of library you use to connect with the API.
  type: string
  required: false
  example: knapsack_pro-ruby
KNAPSACK-PRO-CLIENT-VERSION:
  description: It is the version of the library you use to connect with the API.
  type: string
  required: false
  example: 1.0.0
KNAPSACK-PRO-TEST-SUITE-TOKEN:
  description: Test suite token for your project. You can get it on the user dashboard.
  type: string
  required: true
  example: e5311882cbba506223ee8036fa68dc13
KNAPSACK-PRO-CI-PROVIDER:
  description: It is the name of the CI provider.
  type: string
  required: false
  example: GitHub Actions
