KNAPSACK-PRO-CLIENT-NAME:
  description: It is a name of library you use to connect with API.
  type: string
  required: false
  example: knapsack_pro-ruby
KNAPSACK-PRO-CLIENT-VERSION:
  description: It is a version of library you use to connect with API.
  type: string
  required: false
  example: 1.0.0
KNAPSACK-PRO-TEST-SUITE-TOKEN:
  description: Test suite token for your project. You can get it in user dashboard.
  type: string
  required: true
  example: e5311882cbba506223ee8036fa68dc13
