type: boolean
required: true
example: |
  true
  false
description: |
  Should the request make an attempt to connect to existing queue on the API side? The `attempt_connect_to_queue` param is taken in to account by the API server only if `can_initialize_queue` is `true`.
