type: string
required: true
example: 6e3396177d9f8ca87e2b93b4b0a25babd09d574d
description: |
  The most recent hash commit in your project.

  You are running tests on the codebase with latest commit pointed to the **commit_hash**.
