type: CommitAuthor[]
required: false
example: [{ commits: 1, author: "Jo** Do* <jo**.do*@ex*****.co*>" }]
description: |
  The authors that committed to the repository in the last month. They must be masked with a regexp pattern `/(?<=\w{2})[a-zA-Z]/g`. For example, `John Doe <john.doe@example.com>` should be masked as in the following example.
