type: boolean
required: false
example: |
  true
  false (default)
description: |
  For `true` value it means when you run test suite again for the same commit hash and total number of nodes and for the same branch then you will get exactly the same test suite split as on the last dynamic queue split for particular CI build.

  Thanks to that when tests on one of your node failed then you can retry the node with exactly the same subset of tests that were run on the node in the first place.
