type: integer
required: true
example: 0
description: |
    Index of current CI node where part of the test suite where executed.

    __node_index__ starts from 0 so in case when __node_total__ is 4 then max __node_index__ is 3.
