type: integer
required: true
example: 0
description: |
    Index of current CI node where part of the test suite where executed.

    **node_index** starts from 0 so in case when **node_total** is 4 then max **node_index** is 3.
