type: string
required: true
example: |
  [
    {
      "path": "test/fast/a_test.rb"
    },
    {
      "path": "test/fast/b_test.rb"
    },
    {
      "path": "test/slow/c_test.rb"
    },
    {
      "path": "test/slow/d_test.rb"
    }
  ]
description: |
  JSON array with objects. Each object contains a test file path.

  The example contains all test files in the test suite you want to run in your CI build.

  When `attempt_to_read_from_cache=false`, then the `test_files` field is required to initialize a test suite split on the API side.

  Otherwise, the `test_files` field is not needed. Do not set it in the body to save data transfer and make a fast request.
