type: string
required: true
example: |
  [
    {
      "path": "test/fast/a_test.rb"
    },
    {
      "path": "test/fast/b_test.rb"
    },
    {
      "path": "test/slow/c_test.rb"
    },
    {
      "path": "test/slow/d_test.rb"
    }
  ]
description: |
  JSON array with objects. Each object contains a test file path.

  The example contains all test files in the test suite you want to run in your CI build.

  When `can_initialize_queue=true` AND `attempt_connect_to_queue=false` then `test_files` field is required to initialize a queue on the API side.

  Otherwise, the `test_files` field is not needed. Do not set it in the body to save data transfer and make request faster.
