type: string
required: true
example: 4ae170d5806c331bfab123ca1adaadb3
description: |
  Token for the particular test suite. __Token must be kept private.__

  For instance token for your RSpec test suite. If you have also test written in Cucumber then you will have separate token for Cucumber test suite.
