type: string
required: true
example: |
  [
    {
      "path": "test/fast/a_test.rb"
    },
    {
      "path": "test/fast/b_test.rb"
    },
    {
      "path": "test/slow/c_test.rb"
    },
    {
      "path": "test/slow/d_test.rb"
    }
  ]
description: |
  JSON array with objects. Each object contains test file path.

  Example contains all test files existing in the test suite.
