type: string
required: true
example: fa9602418c626dd0347ccdd488a93ac7d870fa763126fea7fd0c5133a69062a7
description: |
  SHA-256 hash of the user name that started the CI build. Often it's the same person that created the git commit.
