type: integer
required: false
example: 4
description: |
  You can filter by total number of CI nodes you have run CI build on.

  For instance if you parallelized your test suite across 4 machines then __node_total__ is 4.
