#%RAML 0.8
---
title: Knapsack Pro
baseUri: http://api.knapsackpro.com/{version}
version: v1

/build_subsets:
  post:
    description: |
      Endpoint expects partial test suite execution data for particular test build.

      For instance send here data collected after execution half of test suite on the first CI node. Send here also data collected for the second half of the test suite executed on the second CI node.

      We will merge the data automatically to have complete information about particular build.

    queryParameters:
      test_suite_token:
        type: string
        required: true
        example: 4ae170d5806c331bfab123ca1adaadb3
        description: |
          Token for the particular test suite. __Token must be kept private.__

          For instance token for your RSpec test suite. If you have also test written in Cucumber then you will have separate token for Cucumber test suite.
      commit_hash:
        type: string
        required: true
        example: 6e3396177d9f8ca87e2b93b4b0a25babd09d574d
        description: |
          The most recent hash commit in your project.

          You are running tests on the codebase with latest commit pointed to the __commit_hash__.
      branch:
        type: string
        required: true
        example: master
        description: |
          You are running tests on this branch.
      node_total:
        type: integer
        required: true
        example: 4
        description: |
          Total number of CI nodes you have.

          For instance if you want to parallelize your test suite across 4 servers then __node_total__ is 4.
      node_index:
        type: integer
        required: true
        example: 0
        description: |
           Index of current CI node where part of the test suite where executed.

           __node_index__ starts from 0 so in case when __node_total__ is 4 then max __node_index__ is 3.
      test_files:
        type: string
        required: true
        example: |
          [
            {
              "path": "test/fast/a_test.rb",
              "time_execution": 0.2015
            },
            {
              "path": "test/fast/b_test.rb",
              "time_execution": 0.04
            },
            {
              "path": "test/slow/c_test.rb",
              "time_execution": 6.2120
            },
            {
              "path": "test/slow/d_test.rb",
              "time_execution": 4.3703
            }
          ]
        description: |
          JSON array with objects. Each object contains test file path and execution time for the test file.

          Example contains only part of the test suite. The part of tests was executed on the CI node for specified __node_index__.

    responses:
      201:
        body:
          application/json:
            example: Response does not contain any data.
      422:
        body:
          application/json:
            example: |
              // example 1
              {
                "errors": [
                  {
                    "branch": ["parameter is required"]
                  }
                ]
              }

              // example 2
              {
                "errors": [
                  {
                    "node_index": ["must be less than or equal to 1"],
                    "test_files": [
                      {
                        "0": {
                          "time_execution": ["is not a number"]
                        },
                        "1": {
                          "path": ["is too short (minimum is 3 characters)"]
                        }
                      }
                    ]
                  }
                ]
              }
