#%RAML 0.8
---
title: Knapsack Pro
baseUri: http://api.knapsackpro.com/{version}
version: v1
mediaType: application/json

/build_subsets: !include build_subsets/main.raml
/build_distributions: !include build_distributions/main.raml
/queues: !include queues/main.raml
